### ISSUE TITLE
Chrome Blinking Preview Frame

### ISSUE THREAD

**Issue by beauremus** [Unrestricted-Coding/realtime-editor#9]
When using Chrome the preview window blinks as things as edited. I found some limited leads to an older issue and workaround that didn't seem to fix the issue. This is not an issue in Firefox.

**Comment by shadowcodex** [comment]
Ok, that is due to the live rendering. I'll see what I can do to smooth that out.

Does it happen when manually running the session and having live preview disabled?

**Comment by beauremus** [comment]
Yes. There just seems to be something going on with the transition on the update. The old issue was related to CSS transitions in an iframe. Is this possibly related to the way the browser handles ajax?

**Comment by shadowcodex** [comment]
Its probably just the way the browser handles the iframe reloads. I reload the iframe with new data every keystroke.

**Comment by shadowcodex** [comment]
Found the issue. 

This isn't a bug of the editor, but actually the included css file from bootstrap. If you comment out the css file from the bootstrap load then it doesn't flicker... Will research this. And it may be due to cross origin issues.

**Comment by shadowcodex** [comment]
Fixed in commit 61deeebb3f49f307eecd377c82aba88214ae3562
